;;; thank you message table, generated by buildThankYouMessage.ts
; column: 0
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 1
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 2
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 3
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 4
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 5
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 6
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 7
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 8
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 9
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 10
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $54 ; T
dc.b $20 ;  
dc.b $4b ; K
dc.b $20 ;  
dc.b $54 ; T
dc.b $20 ;  
dc.b $20 ;  
dc.b $44 ; D
dc.b $20 ;  
dc.b $77 ; w
dc.b $20 ;  
dc.b $53 ; S
dc.b $20 ;  
dc.b $20 ;  
dc.b $53 ; S
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $63 ; c
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 11
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $68 ; h
dc.b $20 ;  
dc.b $69 ; i
dc.b $20 ;  
dc.b $65 ; e
dc.b $20 ;  
dc.b $20 ;  
dc.b $6f ; o
dc.b $20 ;  
dc.b $61 ; a
dc.b $20 ;  
dc.b $6f ; o
dc.b $20 ;  
dc.b $20 ;  
dc.b $65 ; e
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $72 ; r
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 12
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $61 ; a
dc.b $20 ;  
dc.b $6e ; n
dc.b $20 ;  
dc.b $61 ; a
dc.b $20 ;  
dc.b $20 ;  
dc.b $69 ; i
dc.b $20 ;  
dc.b $73 ; s
dc.b $20 ;  
dc.b $2c ; ,
dc.b $20 ;  
dc.b $20 ;  
dc.b $65 ; e
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $65 ; e
dc.b $74 ; t
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 13
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $6e ; n
dc.b $20 ;  
dc.b $67 ; g
dc.b $20 ;  
dc.b $6d ; m
dc.b $20 ;  
dc.b $20 ;  
dc.b $6e ; n
dc.b $20 ;  
dc.b $6e ; n
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $61 ; a
dc.b $68 ; h
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 14
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $6b ; k
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $67 ; g
dc.b $20 ;  
dc.b $27 ; '
dc.b $20 ;  
dc.b $75 ; u
dc.b $20 ;  
dc.b $20 ;  
dc.b $79 ; y
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $74 ; t
dc.b $61 ; a
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 15
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $73 ; s
dc.b $20 ;  
dc.b $4f ; O
dc.b $20 ;  
dc.b $45 ; E
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $74 ; t
dc.b $20 ;  
dc.b $68 ; h
dc.b $20 ;  
dc.b $20 ;  
dc.b $6f ; o
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $65 ; e
dc.b $6e ; n
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 16
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $66 ; f
dc.b $20 ;  
dc.b $64 ; d
dc.b $20 ;  
dc.b $20 ;  
dc.b $61 ; a
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $2c ; ,
dc.b $20 ;  
dc.b $20 ;  
dc.b $75 ; u
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $64 ; d
dc.b $6b ; k
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 17
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $66 ; f
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $69 ; i
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $72 ; r
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $73 ; s
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 18
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $6f ; o
dc.b $20 ;  
dc.b $46 ; F
dc.b $20 ;  
dc.b $74 ; t
dc.b $20 ;  
dc.b $20 ;  
dc.b $72 ; r
dc.b $20 ;  
dc.b $65 ; e
dc.b $20 ;  
dc.b $74 ; t
dc.b $20 ;  
dc.b $20 ;  
dc.b $6e ; n
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $62 ; b
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 19
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $72 ; r
dc.b $20 ;  
dc.b $69 ; i
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $65 ; e
dc.b $20 ;  
dc.b $61 ; a
dc.b $20 ;  
dc.b $68 ; h
dc.b $20 ;  
dc.b $20 ;  
dc.b $65 ; e
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $79 ; y
dc.b $74 ; t
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 20
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $67 ; g
dc.b $20 ;  
dc.b $45 ; E
dc.b $20 ;  
dc.b $20 ;  
dc.b $61 ; a
dc.b $20 ;  
dc.b $6c ; l
dc.b $20 ;  
dc.b $69 ; i
dc.b $20 ;  
dc.b $20 ;  
dc.b $78 ; x
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $6f ; o
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 21
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $70 ; p
dc.b $20 ;  
dc.b $68 ; h
dc.b $20 ;  
dc.b $64 ; d
dc.b $20 ;  
dc.b $20 ;  
dc.b $6c ; l
dc.b $20 ;  
dc.b $6c ; l
dc.b $20 ;  
dc.b $73 ; s
dc.b $20 ;  
dc.b $20 ;  
dc.b $74 ; t
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $43 ; C
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 22
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $6c ; l
dc.b $20 ;  
dc.b $74 ; t
dc.b $20 ;  
dc.b $69 ; i
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $79 ; y
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $69 ; i
dc.b $53 ; S
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 23
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $61 ; a
dc.b $20 ;  
dc.b $65 ; e
dc.b $20 ;  
dc.b $74 ; t
dc.b $20 ;  
dc.b $20 ;  
dc.b $65 ; e
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $69 ; i
dc.b $20 ;  
dc.b $20 ;  
dc.b $74 ; t
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $74 ; t
dc.b $69 ; i
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 24
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $79 ; y
dc.b $20 ;  
dc.b $72 ; r
dc.b $20 ;  
dc.b $69 ; i
dc.b $20 ;  
dc.b $20 ;  
dc.b $6e ; n
dc.b $20 ;  
dc.b $70 ; p
dc.b $20 ;  
dc.b $73 ; s
dc.b $20 ;  
dc.b $20 ;  
dc.b $69 ; i
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $79 ; y
dc.b $65 ; e
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 25
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $69 ; i
dc.b $20 ;  
dc.b $73 ; s
dc.b $20 ;  
dc.b $6f ; o
dc.b $20 ;  
dc.b $20 ;  
dc.b $64 ; d
dc.b $20 ;  
dc.b $6f ; o
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $6d ; m
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $34 ; 4
dc.b $4b ; K
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 26
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $6e ; n
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $6e ; n
dc.b $20 ;  
dc.b $20 ;  
dc.b $69 ; i
dc.b $20 ;  
dc.b $73 ; s
dc.b $20 ;  
dc.b $74 ; t
dc.b $20 ;  
dc.b $20 ;  
dc.b $65 ; e
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $31 ; 1
dc.b $65 ; e
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 27
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $67 ; g
dc.b $20 ;  
dc.b $31 ; 1
dc.b $20 ;  
dc.b $21 ; !
dc.b $20 ;  
dc.b $20 ;  
dc.b $6e ; n
dc.b $20 ;  
dc.b $73 ; s
dc.b $20 ;  
dc.b $68 ; h
dc.b $20 ;  
dc.b $20 ;  
dc.b $21 ; !
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $6e ; n
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 28
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $39 ; 9
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $67 ; g
dc.b $20 ;  
dc.b $69 ; i
dc.b $20 ;  
dc.b $65 ; e
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $73 ; s
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 29
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $39 ; 9
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $62 ; b
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $6f ; o
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 30
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $34 ; 4
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $6c ; l
dc.b $20 ;  
dc.b $65 ; e
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $75 ; u
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 31
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $65 ; e
dc.b $20 ;  
dc.b $6e ; n
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 32
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $2e ; .
dc.b $20 ;  
dc.b $64 ; d
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 33
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $69 ; i
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 34
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $6e ; n
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 35
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $67 ; g
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 36
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $2e ; .
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 37
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 38
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
; column: 39
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
dc.b $20 ;  
